name: firechat
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: "0.6.0"
  cloud_firestore: "^0.15.0"
  crypto: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
