name: firechat
description: Chat package that has complete chatting functionality using Firebase.
version: 0.0.2
homepage: https://github.com/thruthesky/firechat

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: "0.7.0"
  firebase_auth: "^0.20.1"
  cloud_firestore: ^0.16.0

  crypto: "^2.1.5"

  # Chat room. Scroll adjustment when keypad is open.
  flutter_keyboard_visibility: ^4.0.3

  flutter_chat_bubble: ^1.0.2

  cached_network_image: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
