name: firechat
description: Chat package that has complete chatting functionality using Firebase.
version: 0.0.2
homepage: https://github.com/thruthesky/firechat

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # intl: ^0.16.0
  intl: ^0.17.0
  # firebase_core: "0.7.0"
  # firebase_auth: "^0.20.1"
  # cloud_firestore: "^0.16.0+1"
  firebase_core: ^1.0.3
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.5

  crypto: "^2.1.5"
  # crypto: ^3.0.1

  # Chat room. Scroll adjustment when keypad is open.
  # flutter_keyboard_visibility: ^4.0.6
  flutter_keyboard_visibility: ^5.0.1

  flutter_chat_bubble: ^1.0.2

  cached_network_image: ^2.5.0

  rxdart: ^0.25.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
