part of 'firechat.dart';

const String ROOM_NOT_EXISTS = 'ROOM_NOT_EXISTS';
const String MODERATOR_NOT_EXISTS_IN_USERS = 'MODERATOR_NOT_EXISTS_IN_USERS';
const String YOU_ARE_NOT_MODERATOR = 'YOU_ARE_NOT_MODERATOR';
const String ONE_OF_USERS_ARE_BLOCKED = 'ONE_OF_USERS_ARE_BLOCKED';
const String USER_NOT_EXIST_IN_ROOM = 'USER_NOT_EXIST_IN_ROOM';
const String CHAT_DISPLAY_NAME_IS_EMPTY = 'CHAT_DISPLAY_NAME_IS_EMPTY';
